services:
  mysql:
    image: mysql:8
    container_name: mysql_ludoteca_tp
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ludoteca
    ports:
      - "3306:3306"
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  backend:
    build: ./backend/config
    container_name: backend_app
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    restart: unless-stopped